feat(virtual-host): implement domain restriction
gravitee-io/gravitee-management-webui pull request #1340
Opened 2020-10-13 11:40 UTC by phiz71

If domain restrictions exists on current environment, virtual hosts must respect them and host become mandatory,

Closes gravitee-io/issues#4308

2020-10-24 09:54 UTC, aelamrani requested changes
Did I miss something?

![Capture d’écran 2020-10-24 à 11 54 00](https://user-images.githubusercontent.com/1580262/97078877-adab8c00-15ef-11eb-9cf3-09b4e4674ab9.png)

2020-10-26 10:59 UTC, phiz71 commented
> Did I miss something?
> 
> ![Capture d’écran 2020-10-24 à 11 54 00](https://user-images.githubusercontent.com/1580262/97078877-adab8c00-15ef-11eb-9cf3-09b4e4674ab9.png)

No, a problem in the router. I've fixed it.

2020-10-26 14:03 UTC, ytvnr reviewed
some remarks and questions

2020-10-26 14:07 UTC, phiz71 commented on src/management/api/proxy/apiProxy.controller.ts
> +      for (let i = 0; i < this.domainRegexList.length; i++) {
I'm ok with this.

2020-10-26 14:07 UTC, phiz71 commented on src/management/api/proxy/apiProxy.controller.ts
> +      this.hostPattern = '^((?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+[A-Za-z]{2,6}$';
OK

2020-10-26 14:08 UTC, phiz71 commented on src/management/api/proxy/apiProxy.controller.ts
> +    this.domainRegexList.forEach(regex => host = host.replace(regex, ''));
I can declare a locale variable.

2020-11-03 16:43 UTC, merged