feat(management): contact subscribers as an api publisher
gravitee-io/gravitee-management-webui pull request #1521
Opened 2021-03-29 17:11 UTC by gcusnieux

fix gravitee-io/issues#4896

2021-03-29 17:13 UTC, gcusnieux commented
Recipients selection when
![Capture d’écran 2021-03-29 à 18 22 40](https://user-images.githubusercontent.com/1457497/112874154-dc5bf000-90c2-11eb-88d8-f60214335a92.png)
when 

![Capture d’écran 2021-03-29 à 18 22 55](https://user-images.githubusercontent.com/1457497/112874164-e120a400-90c2-11eb-85c9-e21020b4f90d.png)

2021-03-31 07:36 UTC, ytvnr requested changes

2021-03-31 07:36 UTC, ytvnr commented on src/management/messages/messages.component.ts
> +          role.displayName = `Members with the ${role.name} role of applications subscribed to the API`;
```suggestion
          role.displayName = `Members with the ${role.name} role on subscribing applications`;
```

2021-03-31 09:17 UTC, ytvnr approved these changes

2021-03-31 09:24 UTC, merged